[project]
name = "qllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datasets>=4.0.0",
    "torch>=2.8.0",
    "tokenizers>=0.15.0",
    "xformers>=0.0.23",
]
